version: "3"

volumes:
  postgres_volume_local:
  postgres_volume_prod:
  redis_volume_local:

services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
  redis:
    image: redis:7.2.3-alpine3.18
    volumes:
      - redis_volume_local:/root/redis
#      - redis_volume_local/config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - "local.env"
#    environment:
#      - REDIS_PASSWORD=my-password
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
#  pg-prod:
#    image: postgres:14-alpine3.17
#    env_file:
#      - "prod.env"
#    ports:
#      - "54322:5432"
#    volumes:
#      - postgres_volume_prod:/var/lib/postgresql/data

#  migrator-local:
#     build:
#       context: .
#       dockerfile: migration_local.Dockerfile
#     restart: on-failure
#     volumes:
#       - ./migrations:/migrations
#       - :/bin
#     command: ./goose -dir /migrations postgres host=pg-local port=5432 dbname=auth user=auth-user password=auth-password sslmode=disable status -v
#     environment:
#       DB_HOST: pg-local

  # migrator-prod:
  #   build:
  #     context: .
  #     dockerfile: migration_prod.Dockerfile
  #   restart: on-failure
  #   environment:
  #     DB_HOST: pg-prod
