// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package user

import (
	"database/sql"
)

type User struct {
	ID       int64
	Name     string
	Email    sql.NullString
	Password string
}
